Fixed ch14855 - create LDAP troubleshooter
grokability/snipe-it pull request #10033
Opened 2021-09-02 00:37 UTC by uberbrady

# Description

A lot of our users have problems with getting their initial LDAP configurations right - it's enormously complex and has tons of moving parts. We'd eventually like to get to the point where we have some kind of Wizard interface to help the user figure out the right settings, but we're not quite there yet. So this is just a simple Artisan command with a couple of different options you can set. So we can at least start to vet the general sort-of algorithm to see if it makes sense.

It's a completely separate Artisan command so it shouldn't cause any problems - if you don't like it, don't use it :P

Fixes ch14855

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested against a working Google LDAP configuration, which has some weird timeouts, but generally seems to help
- [ ] It should probably get tested against our development AD server, as that's going to be a pretty common use-case. I haven't done that yet, which is why I've marked this as WIP.

2021-09-02 00:51 UTC, snipe commented
@uberbrady this is still marked as draft - is that intentional?

2021-09-02 01:02 UTC, uberbrady commented
`<singing musical="hamilton" singer="angelica">`Did you intend this? One stroke and you've consumed my waking days`\n` it says - Work In Progress - Draft`\n`with a comma after 'Progress'`\n`You've written - Work in Progress......,`\n`Draft...`</singing>`

2021-09-02 01:02 UTC, uberbrady commented
(yes, I did want to get @Godmartinz to check out our AD LDAP setup and let me know how it looked)

2021-09-02 01:08 UTC, snipe commented
Sigh.

2021-09-02 01:09 UTC, snipe commented
![IMG_0886](https://user-images.githubusercontent.com/197404/131765421-f19a2909-b441-4694-bad5-8fa46d77573a.JPG)

2021-09-08 00:36 UTC, snipe commented
This should still be a draft, yes?

2022-03-08 04:04 UTC, uberbrady commented
@snipe I'm ready to include this on develop - it's additive *only*, it's not even documented, and it shouldn't get in anyone's way. We can start to play with it in anger once v6 comes out. I'm sure it will need at least a few tweaks.

2022-03-08 04:21 UTC, snipe requested changes
One minor nit, but otherwise this looks fantastic. Really, really nice work here, Brady.

2022-03-08 04:21 UTC, snipe commented on app/Console/Commands/LdapTroubleshooter.php
> +            //if($port == 389) { continue; } // FIXME GET RID OF THIS LINE! THIS SUCKS!!!!!!
Should probably get rid of this line :)

2022-03-08 04:24 UTC, merged