Fixes Gh10191 css dropdownmenu
grokability/snipe-it pull request #10728
Opened 2022-02-23 19:20 UTC by Godmartinz

# Description

Corrects color contrasts on dropdown menu from the nav bar  on mobile views.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-23 19:28 UTC, snipe commented on resources/assets/less/skins/skin-black-dark.less
> -.dropdown-menu, .dropdown-menu>li>a {
Do we not need a background color here? Or is that set somewhere else? (Forgive me, it's been a while since I dug into the less files for skins.)

2022-02-23 19:29 UTC, snipe commented on resources/assets/less/skins/skin-black-dark.less
> -.dropdown-menu, .dropdown-menu>li>a {
Would it be better to use the less variables?

2022-02-23 19:50 UTC, snipe requested changes
I have a few comments inline - if you can address those, that would be great - ty!

2022-02-24 18:57 UTC, snipe commented on resources/assets/less/skins/skin-black-dark.less
> -.dropdown-menu, .dropdown-menu>li>a {
@Godmartinz can I get an update here?

2022-02-28 17:22 UTC, Godmartinz commented
background is now darker:
![image](https://user-images.githubusercontent.com/47435081/156029027-0319def5-2211-4ab8-9904-353e7d048ccb.png)

2022-03-02 22:30 UTC, snipe commented
Was this tested on all of the skins (including the light ones)? Also please remove the json files here - we don't need the mix-manifest or package.lock files.

Thanks!

2022-03-02 22:32 UTC, snipe requested changes
See my last comment re: json files

2022-03-03 17:35 UTC, Godmartinz commented
This screenshot is of the black dark mode theme. Just double checked that it has been tested in the  light and dark themes.

2022-03-10 21:02 UTC, merged