WIP adds routes, button, and a bit of logic for the email-list function
grokability/snipe-it pull request #10938
Opened 2022-04-12 23:05 UTC by Godmartinz

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, providing screenshots where practical. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
Adding the ability to email a user a list of all assets, licenses etc. from the user profile screen.

- [ x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-14 17:29 UTC, snipe commented on resources/lang/en/admin/users/general.php
> +    'user_notified'     => 'User has been notified.',
Let's change this to something more specific, like "User has been emailed a list of their currently assigned items."

2022-04-14 17:29 UTC, Godmartinz commented on resources/lang/en/admin/users/general.php
> +    'user_notified'     => 'User has been notified.',
done :)

2022-04-14 17:30 UTC, snipe commented on resources/lang/en/general.php
> +    'asset_serial'          => 'Serial',
We definitely have an existing translation for serial somewhere in the system - better to re-use that.

2022-04-14 17:30 UTC, snipe commented on routes/web/users.php
> +    Route::get(
This should be a POST request, not a GET. You never want to use a GET request for something that actually *does* something, like changing records, sending emails, etc.

2022-04-14 17:31 UTC, snipe commented on routes/web/users.php
> +    )->name('users.print');
This should probably be named something else, since we're not printing, we're emailing.

2022-05-05 20:37 UTC, snipe requested changes
Just a few tweaks I think - otherwise this looks pretty good :)

2022-05-05 20:37 UTC, snipe commented on app/Http/Controllers/Users/UsersController.php
> +    //Should we go with a PDF, was there a command already set up for this somewhere. Ponder on this I must.
Can you yank this comment out?

2022-05-05 20:37 UTC, snipe commented on app/Http/Controllers/Users/UsersController.php
> +        $user = User::where('id', $id)->withTrashed()->first();
Do we want `withTrashedI()` here? Is there a use case where we'd be sending an email to a deleted user?

Also we should be checking that the user actually exists before trying to action on it.

2022-06-29 18:18 UTC, closed without merging