add checkbox to allow skipping a user during
grokability/snipe-it pull request #12124
Opened 2022-11-15 23:58 UTC by Godmartinz

# Description

Adds an `should_autoassign` boolean to the users table to prevent certain users from being auto assigned licenses.

User Edit page:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/47435081/202049840-a92d7c15-16e7-4585-ab28-7bb8d6091b41.png">

Fixes #sc 16946

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-28 22:10 UTC, snipe commented on database/migrations/2022_11_15_232525_adds_should_autoassign_bool_to_users_table.php
> +            $table->boolean('should_autoassign')->nullable(false)->default(0);
Can we change this to `autoassign_licenses` for clarity?

2022-11-28 22:12 UTC, snipe commented on resources/lang/en/admin/users/general.php
> +    'auto_assign_label' => 'User should be skipped during auto assignment commands',
I think it's prefer this to go in the opposite direction, versus the negative. Default that checkbox to checked, set the db default to 1, and change the language to "Include this user when auto-assigning eligible licenses"

2023-01-13 23:03 UTC, snipe requested changes
Pinging you again - there were some changes requested here

2023-01-13 23:03 UTC, snipe commented on app/Console/Commands/CheckoutLicenseToAllUsers.php
> +        $users = User::whereNull('deleted_at')->where('should_autoassign', '==', 0)->with('licenses')->get();
Shouldn't this be 1, no 0?

2023-01-18 16:43 UTC, Godmartinz commented
All changes have been applied

2023-02-22 04:10 UTC, merged