Adds Livewire slack inputs
grokability/snipe-it pull request #12446
Opened 2023-02-02 00:58 UTC by Godmartinz

# Description
Updates the Slack Settings page to use Livewire. this removes `SlackSettingsRequest.php` since the rules have been moved over to the livewire controller. as Well as the ajax call from the API has been moved to the livewire controller as well. Also the `PostSlack()` method has been removed from the SettingsController.

On Integration test:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/47435081/216204050-a6dc9133-86fd-4386-b7cc-7ecd72dfbafa.png">

on bad name of channel:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/47435081/216204194-edaac94e-aec8-49cf-8870-04d03d1829e1.png">

on updating the slack settings:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/47435081/216204271-7f6d6c0f-d6fe-41cf-a8cf-672790834818.png">

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-02-03 00:06 UTC, marcusmoore requested changes
There are some little things to change but overall 🤩

this is always good 😄 
![CleanShot 2023-02-02 at 15 56 27](https://user-images.githubusercontent.com/1141514/216478859-8ae15f6e-ece6-459a-8f91-6ef7c8794751.png)

2023-02-03 00:06 UTC, marcusmoore commented on resources/views/livewire/slack-settings-form.blade.php
> +{{--                                    {{ Form::text('slack_endpoint', old('slack_endpoint', $setting->slack_endpoint), array('class' => 'form-control','disabled'=>'disabled','placeholder' => 'https
Nitpick: can we delete this line?

2023-02-03 00:06 UTC, marcusmoore commented on resources/views/livewire/slack-settings-form.blade.php
> +{{--                                    {{ Form::text('slack_endpoint', old('slack_endpoint', $setting->slack_endpoint), array('class' => 'form-control','placeholder' => 'https://hooks.slack.com/serv
Nitpick: can we delete this line?

2023-02-03 00:06 UTC, marcusmoore commented on resources/views/livewire/slack-settings-form.blade.php
> +{{--                    {{ Form::text('slack_botname', old('slack_botname', $setting->slack_botname), array('class' => 'form-control','disabled'=>'disabled','placeholder' => 'Snipe-Bot')) }}--}}
Nitpick: can we delete this line?

2023-02-03 00:06 UTC, marcusmoore commented on resources/views/livewire/slack-settings-form.blade.php
> +                    <input type="text" wire:model.lazy="slack_endpoint" id="slack_endpoint" class= 'form-control' placeholder="'https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXX'" {{old('slack_e
I think we can remove the extra `'`s in the placeholder so the user doesn't think they have to surround their endpoint in quotes

![CleanShot 2023-02-02 at 15 54 29](https://user-images.githubusercontent.com/1141514/216477537-09776494-8dbc-47df-8a4a-a789022081bb.png)

```suggestion
                    <input type="text" wire:model.lazy="slack_endpoint" id="slack_endpoint" class= 'form-control' placeholder="https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXX" {{old('slack_endpoint', $slack_endpoint)}} ><br>
                @else
                    <input type="text" wire:model.lazy="slack_endpoint" id="slack_endpoint" class= 'form-control' placeholder="https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXX" {{old('slack_endpoint', $slack_endpoint)}} ><br>
```

2023-02-03 00:06 UTC, marcusmoore commented on app/Http/Livewire/SlackSettingsForm.php
> +        // If validation passes, continue to the curl request
I think we should validate here somehow to make sure we're not getting passed a random url or even just gibberish
![CleanShot 2023-02-02 at 15 59 08](https://user-images.githubusercontent.com/1141514/216478036-c970822e-8a56-435a-b3a8-5f55a77d25e2.png)

Since we'll need it in `testSlack()` and `submit()` you can _probably_ move the validation rules to a [`$rules` property on the component](https://laravel-livewire.com/docs/2.x/input-validation#customize-error-message-and-attributes).

(`SettingsController` (line 149-155) for reference.)

2023-02-03 00:06 UTC, marcusmoore commented on resources/views/livewire/slack-settings-form.blade.php
> +                    <input type="text" wire:model.lazy="slack_botname" id="slack_botname" class= 'form-control' placeholder="'Snipe-Bot'" {{old('slack_botname', $slack_botname)}} ><br>
Same placeholder comment as above.

```suggestion
                    <input type="text" wire:model.lazy="slack_botname" id="slack_botname" class= 'form-control' placeholder="Snipe-Bot" {{old('slack_botname', $slack_botname)}} ><br>
                    <p class="text-warning"><i class="fas fa-lock"></i> {{ trans('general.feature_disabled') }}</p>

                @else
                    <input type="text" wire:model.lazy="slack_botname" id="slack_botname" class= 'form-control' placeholder="Snipe-Bot" {{old('slack_botname', $slack_botname)}} ><br>
```

2023-02-06 17:39 UTC, Godmartinz commented on app/Http/Livewire/SlackSettingsForm.php
> +        // If validation passes, continue to the curl request
I just found and used the magical world of the `updated()` hook for real-time validation. This should take care of allowing gibberish before the integration test happens.

2023-02-15 21:27 UTC, merged

2023-02-15 22:52 UTC, snipe commented
Nice work on this, @Godmartinz. I did a little cleanup here #12522. One thing I noticed is that the submit button doesn't get greyed out if the test fails. The the previous version, IIRC, if the test failed, we didn't allow the form to be submitted. 

There are really only two scenarios where that button should be enabled:

1. The test passed
2. The admin has removed ALL fields, effectively disabling slack integration. 

I'll open a SC for you. :)