Fixed Column not found: 1054 Unknown column '0' in 'field list' [sc-20004]
grokability/snipe-it pull request #12599
Opened 2023-03-02 17:28 UTC by inietov

# Description
The API call to Users with method PATCH accepts arrays for the `groups` parameter. But if the array is weirdly formed the users making the call got an error 500. I found hard to validate that the array is properly formed, since this is in the API and a client could pass whatever value they want... so I use a Try/Catch block to the method causing this error, that way the system doesn't crash and returns the exception as an API error.

Fixes [sc-20004]

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
**Test Configuration**:
* PHP version: 8.2
* MySQL version: 8.0.31
* Webserver version: PHP dev server
* OS version: Debian 11

2023-03-02 17:42 UTC, snipe commented
Should we maybe instead initiate a validator to make sure that the ids in the groups array exist in the groups table? It's a bit more code, but would probably be better overall.

2023-03-03 01:55 UTC, inietov commented
I tried with the validator, but to be honest it doesn't change much... I even needed a try/catch to enclose the validator because if a made a PATCH request to the user endpoint with a  injected value in the groups column like this:
``` 
{
     "groups": [[0,1,2]]
}
```

The validator still crash. I think this is the best way... since if the array is well formed, and the group passed doesn't exist, the API just ignores the group.

2023-03-03 02:25 UTC, snipe commented
What's the error you're seeing when the validator crashes?

2023-03-03 03:32 UTC, inietov commented
![image](https://user-images.githubusercontent.com/653557/222624666-29fdf025-22ed-4fa2-bf6d-c20defb6ee1f.png)

2023-03-07 00:23 UTC, snipe commented
Can we try looping through the array that gets passed and validate on each of the group_ids there, to make sure they exist in the `groups` table? 

It's weird that it's showing as:

```
{
     "groups": [[0,1,2]]
}
```

instead of 

```
{
     "groups": [0,1,2]
}
```

but we should maybe be able to decode that array and make sure the next level down is a set of ids that exist in the departments table.

2023-03-07 19:56 UTC, snipe requested changes
I'd like to see if we can come up with slightly tighter validation here. Whatever the format that the groups payload should be in, we:

1) Shouldn't accept anything NOT in that format
2) Should validate that the groups actually exist, otherwise we could end up with bad data

2023-03-07 20:58 UTC, snipe commented
Converting this to draft so I don't accidentally merge it ;)

2023-03-14 16:51 UTC, snipe commented
This looks great - thanks for the extra effort on this to make it even better <3

2023-03-14 16:51 UTC, merged