#20178: Added Dell and Lenovo to warranty link function
grokability/snipe-it pull request #12669
Opened 2023-03-14 20:09 UTC by akemidx

# Description

An extension of #12477 
Dell and Lenovo were added to the list of manufacturers that pop a link to the warranty checker page.

The attemped functionality to insert the serial number upon creating the link was removed, as the links are too complicated and any change to the websites themselves will end up defaulting to the main warranty page. Therefore, to reduce bloat and create a predictable experience, the links go to each manufacturer's respected checker page.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested locally

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-03-20 21:23 UTC, snipe requested changes
Few tiny changes requested :)

2023-03-20 21:23 UTC, snipe commented on resources/views/hardware/view.blade.php
> +                                                        <img src="/img/demo/manufacturers/lenovoicon.png" style="width:25px;height:25px;"><span class="sr-only">Lenovo Warranty Status Lookup</span></i
Can I get this `sr-only` text translated (including the one above that I made for Apple).

Something like `'general.warranty_lookup_mfg' => ':manufacturer Warranty Status Lookup',`

2023-03-22 07:54 UTC, snipe commented
Love it, thank you!

2023-03-22 07:54 UTC, merged

2023-04-16 19:03 UTC, Robert-Azelis commented
Good idea, please consider add HP warranty link https://support.hp.com/us-en/check-warranty

2023-04-24 20:21 UTC, akemidx commented
> Good idea, please consider add HP warranty link https://support.hp.com/us-en/check-warranty
> 
> > <img alt="" width="48" src="/wcc-assets/images/favicon.ico">

Sorry for the delay, I did consider HP, but are instead working on a dynamic way for any manufacturer to have this functionality. 
Instead of adding manufacturers one by one over time.