fixes footer space when customized
grokability/snipe-it pull request #12832
Opened 2023-04-13 19:26 UTC by Godmartinz

# Description
Footer would be covered up by the div wrapper if the footer went more than one line. I added more height to the footer if additional footer is present to solve this issue.
BEFORE:
![image](https://user-images.githubusercontent.com/47435081/223859833-1467dbe2-dead-4a7f-a22a-de6667852a63.png)

AFTER:
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/47435081/223859531-b6129df2-f940-433f-b00e-0a3850c7f754.png">

Fixes #SC-15580

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-04-16 12:36 UTC, snipe requested changes
This still seems a little brittle to me. I'd think it shouldn't need to be hard-coded, but would instead increase as the number of lines increase, especially since that section takes some amount of markdown, IIRC

2023-04-17 16:50 UTC, Godmartinz commented
Ok, I'll see what I can conjure up 👍

2023-04-17 19:03 UTC, Godmartinz commented
Went with display:flex and now it dynamically adjusts with the size of the footer content or media size.

2023-04-17 19:12 UTC, Godmartinz commented
shoot. 1 sec found a visual bug 🙁

2023-04-17 19:47 UTC, Godmartinz commented
Ok the support footer text aligns to the right, as it should.

2023-04-17 21:28 UTC, snipe commented on resources/views/layouts/default.blade.php
> +                <div class="pull-text-right hidden-xs">
Do we want to actually hide this on `xs` breakpoints?

2023-04-18 03:11 UTC, merged

2023-04-18 03:59 UTC, snipe commented
This is already merged, but I may have to revert it. It's making the spacing at the bottom way too big. See SC-23134