Feature/sc 14441
grokability/snipe-it pull request #13480
Opened 2023-08-16 19:41 UTC by Godmartinz

# Description
This adds two methods `changedInfo()` and `bulkChangedInfo()`.

`changedInfo()` and `bulkChangedInfo()` are similar except `changedInfo()` utilizes the model scopes for new changes.
array keys have been renamed to be more readable (e.g `rtd_location_id` is now `Default Location`) in the History tab of an asset.
If an asset never had a supplier, default location, company, or location already assigned to it, it will be noted as 'unassigned' (example below)

Before:
<img width="1780" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/6f347d6b-83f5-4262-9c73-d3d4acea56c8">

After:
<img width="1780" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/120dfa18-22a4-4571-9b74-141b1c53fdb6">

Fixes #sc-14441

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-08-16 20:51 UTC, marcusmoore requested changes
Overall this looks good. A couple minor things (the missing Supplier import is the biggest)

2023-08-16 20:51 UTC, marcusmoore commented on app/Http/Controllers/Assets/BulkAssetsController.php
> +            $changed['supplier_id']['old'] = $changed['supplier_id']['old'] ? Supplier::find($changed['supplier_id']['old'])->name : 'unassigned';
You gotta import `Supplier`.

2023-08-16 20:51 UTC, marcusmoore commented on app/Http/Controllers/Assets/BulkAssetsController.php
> +     * @return void
I think the type hint should be `array`.

2023-08-16 20:51 UTC, marcusmoore commented on app/Observers/AssetObserver.php
> +     * @return void
I think the type hint should be `array`.

2023-08-17 08:07 UTC, Godmartinz commented
Whoops on the import, I swear it worked! 😅

2023-08-17 18:01 UTC, Godmartinz commented
Closing this because, @spencerrlongg made a good point, that I am changing the way data is being stored in the DB and not adjusting old data. It would be better if I put this method inside of the actionlogtransformer and did my changes basically on the front end not the back end. Love the idea!

2023-08-17 18:01 UTC, closed without merging