Added threshold notifications and min qty for Asset models
grokability/snipe-it pull request #13526
Opened 2023-08-24 17:48 UTC by Godmartinz

# Description
This adds a minimum quantity threshold for Asset Models. Also updates the notifcations to include Asset Models.

<img width="434" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/22d726e1-c11f-44aa-92f2-f8682dbfd73b">
<img width="848" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/b3cd8227-ea58-4062-beb8-14d38fb415ab">

Fixes #sc-19826

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-08-28 18:20 UTC, snipe commented on app/Http/Transformers/ActionlogsTransformer.php
> +        //\Log::info("Clean Meta is: ".print_r($clean_meta,true));
Can we pull these commented out lines?

2023-08-28 18:24 UTC, snipe requested changes
I think we also need to add `min_amt` to the `fillable` array in the `AssetModel` model since we use ` $assetmodel->fill($request->all());` in the API, otherwise additions/updates via the API won't be able to access that value. (Unless it's already in there and I just missed it.)

Otherwise this looks pretty solid.

Not for this PR, but we should also see about adding models to the inventory alert emails.

2023-08-29 18:30 UTC, Godmartinz commented
`min_amt` is already added to `fillable` in the `AssetModel` model. Also, for the Inventory Alert email, where would the asset_model quantity info need to be sent? My understanding is that it goes to the `Helper:checkLowInventory()`

2023-08-30 14:01 UTC, snipe commented
Ah, you're right, my bad. The GH diff made it look weird. If you can yank those commented lines out, this looks good to go.

2023-09-11 16:37 UTC, snipe commented
Looks like we have a merge conflict now

2023-09-11 16:38 UTC, snipe commented
Nice, quick as a bunny :)

2023-09-11 16:40 UTC, Godmartinz commented
Also, running the low inventory command recognizes and send out an email for asset models. 
<img width="1104" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/62e38fa1-e114-4b67-8aa4-a0b3f0bedd34">

2023-09-11 16:55 UTC, snipe commented
The chipper test is failing on this, but I think it's related to an earlier merge.

2023-09-11 16:55 UTC, merged