Fixed ErrorException: Attempt to read property "id" on null (rollbar #3541)
grokability/snipe-it pull request #13549
Opened 2023-08-30 19:28 UTC by inietov

# Description
For some reason, the notification for license seats checkins breaks, the rollbar only shows occurrences over the demo so I think it's related to that factor. But I added the null coalescing operator anyway, doesn't hurt to be cautious.

Fixes rollbar #3541

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
**Test Configuration**:
* PHP version: 8.1
* MySQL version: 8.0.31
* Webserver version: PHP dev server
* OS version: Debian 12

2023-08-30 20:35 UTC, marcusmoore approved these changes
This is indeed an odd error and is so sporadic it probably lines up with the demo resetting.

Help my before-lunch brain process this: Is it possible that `$event->checkoutable` is null but `$event->checkedOutTo` matches a user and ends up deleting their pending acceptances? I don't think so because the database wouldn't match on `checkoutable_id = null` right?

Approving assuming that is true 😅

2023-08-30 21:25 UTC, inietov commented
@marcusmoore  Yeah... looks kind of dangerous. But assuming a normal behaviour, 'normally' we don't store any of those as null, I suppose a bug can happen somehow... maybe is safer to check the properties of $event before get the acceptances? If no checkoutTo nor checkoutable, we don't even query the DB...

Thanks for your review!!

2023-08-30 23:04 UTC, marcusmoore commented
That's good thinking but I _think_ its ok to leave as is.

2023-09-05 19:27 UTC, inietov commented
@snipe good day, what you think. I should check the $event before the query? or is safe to merge as is?

2023-09-13 18:32 UTC, marcusmoore requested changes
> maybe is safer to check the properties of $event before get the acceptances? If no checkoutTo nor checkoutable, we don't even query the DB...

Reading this again and knowing we've had a couple quirky rollbars recently I feel like checking `$event` to make sure `checkoutTo` and `checkoutable` are both populated before firing the query, like you said, is safer and will lead to a smaller chance of a bug slipping through in the future.

2023-09-13 22:36 UTC, inietov commented
Sure!!, I just add that condition.

2023-09-13 23:09 UTC, marcusmoore approved these changes
I dig it 😄

2023-09-14 11:50 UTC, merged