Default Locale value changed to en-US
grokability/snipe-it pull request #14456
Opened 2024-03-19 20:07 UTC by akemidx

# Description
The default value for a locale coule be set to 'en'. This changes that default to be 'en-US' which is in line with the current standard.

Fixes # (issue)
SC-25079

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
created and ran migration, using tableplus to confirm the new default value of 'en-US' for the locale column

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-20 01:41 UTC, snipe commented
Users table already has a locale column tho - can you help me understand what you’re trying to do here?

2024-03-21 00:03 UTC, snipe requested changes
Still hoping for a follow up to my question here :)

2024-03-21 02:01 UTC, akemidx commented
so we are changing the locale column to no longer default off of the settings, and possibly end up with a en, and instead default to en-US, which is the standard formatting we moved to.

This PR is from what I gathered off of convo plus what little there is in the linked SC.

2024-03-26 12:55 UTC, snipe commented
I think we also missed the settings table

2024-03-28 21:47 UTC, snipe commented
Nice work!

2024-03-28 21:47 UTC, merged