Added #14426: Makes all Manufacturer links dynamic, not just warranty lookup
grokability/snipe-it pull request #14470
Opened 2024-03-21 03:55 UTC by DrekiDegga

# Description

This makes all manufacturer links dynamic just like warranty lookup.

Added #14426 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I've tested working on latest from my test environment.

**Test Configuration**:
* PHP version: 7.4.33
* MySQL version 10.11.4-MariaDB-1~deb12u1 Debian 12
* Webserver version 2.4.56-1~deb11u2
* OS version Debian 12

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-03-21 12:01 UTC, snipe requested changes
I think there's some duplication we can clean up in this.

2024-03-21 12:01 UTC, snipe commented on app/Presenters/AssetPresenter.php
> +    {
I think we can probably combine these two, no? It's effectively the same code repeated.

2024-03-22 00:52 UTC, DrekiDegga commented
@snipe  Sorry about that. I believe I've made the requested changes by merging the Dynamic URL Functions in AssetPresenter.php.

2024-03-26 11:35 UTC, snipe commented
This looks a lot better, thank you. But c an you retarget to `develop`, per the developer docs?

2024-03-26 13:08 UTC, closed without merging