Fixed: Header Dropdown Menus had no hover coloring in dark themes
grokability/snipe-it pull request #14558
Opened 2024-04-04 20:08 UTC by akemidx

# Description
When using a dark theme, the drop down menus in the header bar would not show color when the options were hovered, except within the last breakpoint that hides the left side bar. This fix adds that styling back in so it is consistent between all screen widths.

Fixes #14519

old
<img width="370" alt="Screenshot 2024-03-28 at 5 53 51 PM" src="https://github.com/snipe/snipe-it/assets/116301219/9a82ae06-1e9d-434b-b8aa-b6b1cee45eb8">

updated
<img width="242" alt="Screenshot 2024-03-28 at 5 17 40 PM" src="https://github.com/snipe/snipe-it/assets/116301219/3bf0b40f-d917-4846-9df9-46b52dd11b27">

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
visual testing on a throwaway test branch.

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-04-08 04:00 UTC, snipe commented
I thought @Godmartinz had previously addressed this. @Godmartinz, can you take a look and see what might have caused a regression?

2024-04-08 16:32 UTC, Godmartinz commented
Yea from my git-blame sleuthing I was the last one in there. So I must of inadvertently messed this up 🥴 . @akemidx changes look good here though, might want to share pictures of the other dark themes as well though.

2024-04-08 16:34 UTC, snipe commented
@Godmartinz ahh, you know me all too well :D

2024-04-08 16:35 UTC, Godmartinz requested changes

2024-04-08 16:35 UTC, Godmartinz commented on resources/assets/less/skins/skin-blue-dark.less
Share a screenshot of each of these to show how it looks now. 👍

2024-04-08 22:22 UTC, akemidx commented
<img width="228" alt="Screenshot 2024-04-08 at 6 19 45 PM" src="https://github.com/snipe/snipe-it/assets/116301219/71319315-f681-4ac0-bbda-0550342178f5">
<img width="261" alt="Screenshot 2024-04-08 at 6 20 01 PM" src="https://github.com/snipe/snipe-it/assets/116301219/df4ae2b9-fe26-475d-b1e6-5c4b3fa7812f">
<img width="245" alt="Screenshot 2024-04-08 at 6 20 19 PM" src="https://github.com/snipe/snipe-it/assets/116301219/4946670e-b16c-4f73-ba42-ae93419bc03d">
<img width="304" alt="Screenshot 2024-04-08 at 6 20 38 PM" src="https://github.com/snipe/snipe-it/assets/116301219/1becb27d-6122-4f4d-a5e0-1e970f59a798">
<img width="283" alt="Screenshot 2024-04-08 at 6 20 52 PM" src="https://github.com/snipe/snipe-it/assets/116301219/cf8e418b-419a-47bf-a6a7-50c3d497bc2b">

2024-04-08 22:28 UTC, akemidx commented
<img width="277" alt="Screenshot 2024-04-08 at 6 26 55 PM" src="https://github.com/snipe/snipe-it/assets/116301219/fe289d60-2729-4049-bdc6-2bdcb1e72d99">

2024-04-09 15:29 UTC, snipe commented
Those whites don't look consistent across the skins? Some seem like a very light gray, some are a proper white? Can we correct that? I'd think we want the higher contrast version (so white)

2024-04-09 17:56 UTC, akemidx commented
yes we can fix that. I believe the text is being pulled directly from the prior settings, but I can make sure they are all the higher contrast white accross the board.

2024-04-11 14:35 UTC, merged