Refactored due/overdue for audit, added due/overdue for checkin API endpoint and GUI
grokability/snipe-it pull request #14655
Opened 2024-04-26 18:20 UTC by snipe

Whew. This got a lot messier and bigger than I had intended. 

- Refactors the `/api/v1/hardware/audits/due` and  `/api/v1/hardware/audits/overdue` endpoints
- Added the `/api/v1/hardware/checkins/due` and  `/api/v1/hardware/checkins/overdue` endpoints 
- Added a UI interface for the new due/overdue checkins
- Added badge numbers to the sidebar with counts for checkins and audits
- Changed the badges to be more consistent with our other badges
- Changes the Due for Audit UI into a tabbed interface so we can have both Due/Overdue for Audit *and* Checkin without adding too much more stuff to that side menu

<img width="1702" alt="Screenshot 2024-04-26 at 7 20 03 PM" src="https://github.com/snipe/snipe-it/assets/197404/24134be5-8ddb-46b3-9be2-2263dbb30432">

### To do eventually:
- Refactor the Notifications for expected checkins to use the new model scopes.
- See if we can't make that sidenav hover width a little bigger for less wrapping

2024-04-29 23:36 UTC, marcusmoore commented on tests/Feature/Api/Assets/AssetIndexTest.php
I'm just diving in but I wanted to share this first:

I think we can increase confidence in these tests by creating an asset(s) in each "status" and then querying to make sure we only get back the ones expected. So the outline for a test might look like

1. Create an asset that has upcoming audit
2. Create an asset that is overdue for audit
3. (maybe) Create an asset in another state that shouldn't show up?
4. Send queries with `upcoming_status` set to `overdue`, `due-or-overdue`, `due`
5. Check if the asset ids you expect from the assets created above are included and the ones that shouldn't be included aren't.

The increased confidence comes from knowing the test created assets that shouldn't be returned and checking that they weren't.

2024-04-29 23:38 UTC, marcusmoore commented on tests/Feature/Api/Assets/AssetIndexTest.php
> +        $this->assertTrue(Asset::count() === 3);
Another quick note: I think we can remove these assertions and trust the factories worked as expected. If they stop working for some reason then most of the tests will blow up 😅

2024-04-30 00:10 UTC, marcusmoore requested changes
I did a pure-code review and found a couple changes. Going to pull it up and fully test in a browser soon.

2024-04-30 00:10 UTC, marcusmoore commented on app/Console/Commands/SendExpectedCheckinAlerts.php
> +        $interval = $settings->audit_warning_days ?? 0;
`$settings` is undefined here. We can pull line 48 up and be set.

2024-04-30 00:10 UTC, marcusmoore commented on tests/Feature/Api/Assets/AssetIndexTest.php
> +use Carbon;
```suggestion
use Carbon\Carbon;
```

2024-04-30 00:10 UTC, marcusmoore commented on resources/views/layouts/default.blade.php
> +                                            <badge class="badge">
I see `<badge>` was changed to `<span>` in `hardware/view.blade.php`. Should these be `span`s?

2024-04-30 00:10 UTC, marcusmoore commented on app/Http/Middleware/AssetCountForSidebar.php
> +            $total_overdue_for_audit = Asset::OverdueForAudit($settings)->count();
Double-check but `$settings` shouldn't be needed here:

```suggestion
            $total_overdue_for_audit = Asset::OverdueForAudit()->count();
```

2024-04-30 00:10 UTC, marcusmoore commented on app/Http/Middleware/AssetCountForSidebar.php
> +            $total_overdue_for_checkin = Asset::OverdueForCheckin($settings)->count();
Double-check but `$settings` shouldn't be needed here:

```suggestion
            $total_overdue_for_checkin = Asset::OverdueForCheckin()->count();
```

2024-04-30 00:10 UTC, marcusmoore commented on app/Http/Controllers/Api/AssetsController.php
> +                        $assets->OverdueForAudit($settings);
Double-check but `$settings` shouldn't be needed here:

```suggestion
                        $assets->OverdueForAudit();
```

2024-04-30 00:10 UTC, marcusmoore commented on resources/views/hardware/checkin-due.blade.php
> +@stop
This is done elsewhere but I'm not sure why...I think we can put the logic in `title0` directly in `title`?

2024-05-02 11:37 UTC, snipe commented on app/Console/Commands/SendExpectedCheckinAlerts.php
> +        $interval = $settings->audit_warning_days ?? 0;
I tested this a bunch of times - not sure why it didn't throw an error if it's not defined.

2024-05-02 12:11 UTC, merged