Fixes/move debugbar back to dev
grokability/snipe-it pull request #14933
Opened 2024-06-21 20:25 UTC by snipe

This *should* allow us to move the debugbar back into `require-dev`, but I admit it's acting sort of weird on my end? Even when I run `composer install --no-dev`, the debugbar still shows up. I wouldn't mind some extra eyes on this one. 

Basically, since it's now just a dev dependency, we had to change the disabling on exports to not try to load up the debugbar when we're building the streamed CSV.

2024-06-21 20:27 UTC, snipe commented
Hm, looks like this is breaking the docker builds :-/

2024-06-21 20:29 UTC, snipe commented
And regular tests. Super. I'm sure it's my local that locked in a version.

2024-06-21 20:38 UTC, snipe commented
```
✨snipe@chodeblossom✨ snipe-it  (fixes/move_debugbar_back_to_dev) $ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/view[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.20) does not satisfy that requirement.
    - illuminate/view[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.20) does not satisfy that requirement.
    - illuminate/view[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.20) does not satisfy that requirement.
    - Root composer.json requires laravelcollective/html 6.2 -> satisfiable by laravelcollective/html[v6.2.0].
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.9.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.10.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.10.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.11.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.12.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.13.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.13.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.13.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.13.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.14.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.16.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.17.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.19.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.21.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.21.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.22.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.23.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.23.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.24.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.25.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.25.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.25.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.26.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.26.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.26.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.27.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.28.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.29.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.30.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.30.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.31.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.32.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.32.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.33.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.34.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.34.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.34.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.35.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.36.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.37.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.37.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.37.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.37.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.38.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.38.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.38.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.39.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.40.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.41.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.42.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.43.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.44.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.45.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.45.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.46.0 ( [...]

2024-06-24 19:39 UTC, marcusmoore commented
@snipe digging into this now but heads up: there are some conflicts to resolve...

2024-06-24 19:42 UTC, snipe commented
I can fix those conflicts, no worries

2024-06-24 20:05 UTC, marcusmoore requested changes
Ah...I think we have to re-think the way we're disabling debugbar...

2024-06-24 20:05 UTC, marcusmoore commented on .env.example
> +APP_DEBUG=false
This might not be a big deal but I think `APP_DEBUG` at the top, near `APP_ENV` is so common in Laravel application that moving it down here would confuse people 😅

2024-06-24 20:05 UTC, marcusmoore commented on app/Http/Controllers/Licenses/LicensesController.php
> +        config(['debugbar.enabled' => false]);
I don't think this is working like expected. I dropped this at the top of the `DashboardController@index` method and the dashboard still had debugbar show up...

At this point I think debugbar is past taking `config` into account and `Debugbar::disable()` is actually needed to disable it...

Maybe we should make a `Helper::disableDebugbar()` that checks in debugbar is install and then disables it if it is?

2024-06-24 20:05 UTC, marcusmoore commented on app/Http/Controllers/ReportsController.php
> +        config(['debugbar.enabled' => false]);
Same comment as above.

2024-06-24 20:05 UTC, marcusmoore commented on app/Http/Controllers/Users/UsersController.php
> +        config(['debugbar.enabled' => false]);
Same...

2024-06-24 20:05 UTC, marcusmoore commented on composer.lock
This includes updates to other packages. Probably ok just making sure you're aware.

2024-06-27 12:14 UTC, closed without merging