Added Depreciation Percentage as an option
grokability/snipe-it pull request #15100
Opened 2024-07-16 20:04 UTC by Godmartinz

# Description
This adds the ability to calculate depreciations by percentage. which takes the purchase cost and grabs the percentage and substitutes it in for the amount. the current formula has not changed. this just adds a private method `calculateDepreciation()` to handle this math.

A percentage option has been added to Depreciations:
<img width="579" alt="image" src="https://github.com/user-attachments/assets/cd378579-b307-4229-9be6-82f0980117fd">

Floor Value as an amount or percentage:
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/72c15da2-6451-4990-ac9a-ffdf31fd05cf">
Error if you go outside of 0-100%:
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/e6ae8007-1c86-4fd4-8994-425ba9a07e9b">

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-07-17 17:17 UTC, snipe requested changes
This looks great - can you add in a test or two here as well?

2024-07-17 23:15 UTC, akemidx approved these changes
This looks good! Math seems solid and the now() variable seems to be fine for what we wanna do.

2024-07-23 18:54 UTC, Godmartinz commented
@snipe added a test for amount and percentage 👍

2024-07-24 18:22 UTC, snipe commented on app/Http/Controllers/DepreciationsController.php
> +                        $fail('The depreciation minimum must be between 0 and 100 when depreciation type is percentage.');
This needs to be localized into english.

2024-07-24 18:22 UTC, snipe commented on app/Http/Controllers/DepreciationsController.php
> +                        $fail('The depreciation minimum must be between 0 and 100 when depreciation type is percentage.');
Same here

2024-07-24 19:07 UTC, Godmartinz commented on app/Http/Controllers/DepreciationsController.php
> +                        $fail('The depreciation minimum must be between 0 and 100 when depreciation type is percentage.');
it is so 👍

2024-08-12 09:10 UTC, merged