Fixed: Emails Not Sending to Admin CC when User email blank
grokability/snipe-it pull request #15113
Opened 2024-07-17 23:46 UTC by akemidx

# Description
Emails were not firing when a user had no email, but an admin had a CC email set.
This adds a check for that admin CC email, instead of relying solely on the user's email not being blank.

Emails should now properly fire under those conditions.

[Fixes # (25753)](https://app.shortcut.com/grokability/story/25753/if-the-cc-email-has-a-value-send-checkout-checkin-emails-even-when-checked-out-to-a-target-that-does-not-have-an-email-address)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-07-18 16:47 UTC, snipe requested changes
This looks good - can we get some tests around this tho?

2024-07-18 17:43 UTC, marcusmoore commented
> can we get some tests around this tho

@akemidx adding a new test case method to `Tests\Feature\Notifications\Email\EmailNotificationsUponCheckinTest` and then creating and adding a similar test method to `Tests\Feature\Notifications\Email\EmailNotificationsUponCheckoutTest` would be the way to go. Let me know if you want some help on it.

2024-07-18 18:41 UTC, akemidx commented
yep, will do!

2025-05-22 17:08 UTC, marcusmoore commented
This should be handled in #16932

2025-05-22 20:07 UTC, closed without merging