adds status labels to confirmation emails
grokability/snipe-it pull request #15192
Opened 2024-07-30 16:23 UTC by Godmartinz

# Description

This adds the asset's status to accepted and declined asset notifications

Accepted:
<img width="565" alt="image" src="https://github.com/user-attachments/assets/aafadc19-cdfe-4b1c-a0a3-dae69d1acd76">

Declined:
<img width="565" alt="image" src="https://github.com/user-attachments/assets/1d07649a-adf9-44db-a564-9287e22d6b0a">

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-07-31 07:55 UTC, snipe commented
Why you bork tests??

2024-07-31 20:23 UTC, spencerrlongg commented on app/Notifications/CheckinAssetNotification.php
> +                'status'        => $this->item->assetstatus->name ?: '',
You should be able to use it in these spots too, @Godmartinz - just for uniformity and simplification

2024-08-01 18:47 UTC, spencerrlongg approved these changes
Without actually testing, this looks good to me. Let me know if you'd like me to actually test it out.

2024-08-13 15:24 UTC, snipe requested changes
Can we pull the indent on the new section in the mail blades? I've seen them parse funny in the past, since it's markdown and not HTML.

2024-08-13 17:21 UTC, Godmartinz commented
indents removed 👍

2024-08-13 17:23 UTC, snipe commented
Perfect, ty! (I never quite figured out what triggered the “sometimesy-ness” of those markdown blades failing, it would happen kinda randomly. Indents in markdown are block quotes, so I sort of get it, but was always hard to predict.)

2024-08-13 17:24 UTC, merged