fixes dashboard box overflow
grokability/snipe-it pull request #15206
Opened 2024-08-01 17:35 UTC by Godmartinz

# Description
This creates a class of `dashboard` that is applied to all the box menu options on the dashboard that deals with text overflow.
Before:
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/15bef89c-3d89-4bfc-aa7c-8e0360df875d">

After:
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/68d1f508-aa4a-4099-8444-b5258eab9920">

Fixes #15197

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-08-02 20:10 UTC, snipe commented
I'm not seeing the ellipses here, only the word being cut off. Do we perhaps to need some additional padding in there so we're not smooshing it right up against the inner edge of the box?

2024-08-02 20:11 UTC, snipe commented
(Also, what's happening with that pie chart on the "after" pic?

2024-08-13 14:52 UTC, snipe commented
It also looks like it goofed with the alignment, where it's now center aligned instead of left aligned.

2024-08-13 14:53 UTC, snipe requested changes
Just a few changes in the comments

2024-08-13 17:09 UTC, Godmartinz commented
@snipe so I fixed the box issue around the pie chart and recent activity and the text alignment, but I'm having issues making the ellipsis appear. i've applied `display` , a `width`, `white-space: nowrap`, and `overflow` with the `text-overflow` as recommended but I still get nothing 🤔

2024-08-13 17:14 UTC, snipe commented
Okay,  no problem. I’ll take a look after our break tonight.

2024-08-13 17:16 UTC, Godmartinz commented
Im wondering if it applies to missing letters of a word or only full words? Because its only two letters that get cut off 🤔

2024-08-16 10:10 UTC, merged