replace env with config variable for from address
grokability/snipe-it pull request #15839
Opened 2024-11-18 18:55 UTC by Godmartinz

# Description
This replaces the env variable being used in the from field for mail notifications with the config variable `mail.from.address`

Fixes #15834

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-11-19 10:51 UTC, snipe commented
Looks like we have some failing tests here - can you take a look?

2024-11-19 17:19 UTC, Godmartinz commented
@snipe tests are good now

2024-11-20 13:54 UTC, snipe commented
Why did this end up back in draft?

2024-11-20 15:01 UTC, marcusmoore commented
Not ready to go as is. Planning on wrapping up today.

2024-11-20 21:12 UTC, marcusmoore requested changes

2024-11-20 21:12 UTC, marcusmoore commented on config/mail.php
> +        'address' => env('MAIL_FROM_ADDR', env('MAIL_ENV_FROM_ADDR')),
Let's keep this as it was before. We talked this through and `MAIL_ENV_FROM_ADDR` wouldn't be available to us to use here.

```suggestion
        'address' => env('MAIL_FROM_ADDR', null),
```

2024-11-20 22:27 UTC, Godmartinz commented
@marcusmoore @snipe should be good to go now.

2024-11-20 23:14 UTC, marcusmoore approved these changes
I haven't tested this via docker myself but I believe this is the fix. 👍🏾

2024-11-21 14:41 UTC, merged