Impprove imports
grokability/snipe-it pull request #15898
Opened 2024-11-28 10:52 UTC by bryanlopezinc

# PR Summary

- Validate input options when importing items from the CLI.
 - Validate the import type to prevent errors when an invalid type is provided, applicable to both CLI and API endpoints.
 - Fixed an issue in the import command where a success message was returned even when the import file did not exist.
- Remove the deprecated method fetchOne

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-12-19 22:44 UTC, snipe commented
Hiya - looks like there's a merge conflict here - can you take a look?

2025-02-11 14:14 UTC, uberbrady requested changes
Thank you so much for this! Not a lot of people use the command-line importer, but for those that do, it's important that we don't break it - and especially with your new tests, that's going to be a lot less likely in the future. I did have a couple of small issues, mostly about bits of verbiage and naming of things (which, as you probably know, is one of the hardest problems in computer science). But let me know what you think about that feedback and how you want to go, and then we'll start to do some testing on our end so that we can get this merged. This is really lovely code, thank you so much for your contribution!

2025-02-11 14:14 UTC, uberbrady commented on app/Console/Commands/ObjectImportCommand.php
> +            $this->rules(),
Since we only ever use the rules() function in one place, you could just embed them right here if you wanted. Not a dealbreaker though.

2025-02-11 14:14 UTC, uberbrady commented on app/Console/Commands/ObjectImportCommand.php
> +            $this->messages()
Same here with the messages, but again, not a dealbreaker.

2025-02-11 14:14 UTC, uberbrady commented on app/Console/Commands/ObjectImportCommand.php
> +            ['email_format', null, InputOption::VALUE_REQUIRED, 'The format of the email addresses that should be generated. Options are <info>firstname.lastname</info>, <info>firstname</info>, <info
I haven't seen this `<info>` thing before in command-line stuff, but I'm sure it must work or you wouldn't have done it  :) - but we'll be testing to see how it goes.

2025-02-11 14:14 UTC, uberbrady commented on app/Http/Requests/ItemImportRequest.php
> +        $importer = Factory::make($filename, $this->input('import-type'));
I like this, but the name `Factory` here is confusing since that's usually used in the context of testing. Additionally, I feel like, based on how simple the Factory is, it could be just a static method on the `Importer` class - but we can't call it `factory()` since that's actually used in testing. Maybe something like `Importer::makeImporter()`? But that sounds janky. `Importer::makeSpecifcImporter`? I dunno. But something along those lines should probably work better.

2025-02-11 14:14 UTC, uberbrady commented on app/Http/Requests/ItemImportRequest.php
> -        $classString = "App\\Importer\\{$class}Importer";
I have *always* felt really uncomfortable with the way this works - I really appreciate that you took the time to fix it! Your way is so much better!

2025-02-11 14:14 UTC, uberbrady commented on app/Importer/Importer.php
> +        $headerRow = $this->csv->nth(0);
I really hate that the CSV people make us do this - but that's not your fault. I get the same deprecation warning in PHPStorm when I look at this line, so this is probably the right thing to do. Sigh.

2025-02-11 14:14 UTC, uberbrady commented on app/Importer/MimeTypes.php
> +class MimeTypes
This is another one that is only used once - so we _could_ inline it above if we wanted. But if you have plans or ideas on how to re-use this file elsewhere in the system in the future then I'm fine with it being a separate file. Again, not a dealbreaker for me. (Just, when we're troubleshooting, we often don't like to have to be flipping back and forth between a bunch of files - and we do a *LOT* of troubleshooting).

2025-02-11 14:14 UTC, uberbrady commented on app/Importer/Type.php
> +enum Type: string
I'm fine with this being an enum, but I don't like the `Type` name here - it's just going to be too confusing. Can we rename it to `ImportType` or something like that? It can continue to live here - that's fine, since it really does only have to do with importing - but if you wanted to put it into `App\Enums` that would be OK too.

2025-02-11 14:14 UTC, uberbrady commented on tests/Feature/Console/ImportItemsCommandTest.php
> +<?php
LOVE THIS!!!!!!!!!!!!!!!!!!!!!!

2025-02-11 14:14 UTC, uberbrady commented on tests/Feature/Importing/Api/GeneralImportTest.php
> +    public function testWillReturnValidationErrorWhenImportTypeIsInvalid()
Nice! Love more tests :)

2025-06-02 01:23 UTC, snipe commented
Hi @bryanlopezinc - I think @uberbrady had some comments/nitpicks - do you think you'll have time to look at those and resolve conflicts?

2025-06-18 05:54 UTC, bryanlopezinc commented
Sorry for the late reply, I’ve been busy with stuff. Thanks for the wonderful feedback, @uberbrady. I’m going to close this since it’s not used by a lot of people and to avoid breaking changes. Looking forward to more contributions!

2025-06-18 12:16 UTC, uberbrady commented
@bryanlopezinc do you mind if I re-open this? I really *do* want these changes. I might tweak some stuff here and there, but I'll leave this mostly intact - I think maybe just renaming a few things.

2025-06-18 12:19 UTC, uberbrady commented
(I'm re-opening this for now just to keep track of it and keep it on our radar, we can re-close it again if needed)

2025-08-26 11:50 UTC, snipe commented
@uberbrady - can we revisit this one and make a decision? I think this seems good enough for now, but we can discuss.

2026-03-06 09:14 UTC, snipe commented
@uberbrady @bryanlopezinc - sorry for the delay in following up with this. We have some conflicts, but if those can get resolved, I think this looks pretty good. (We've made some improvements/changes to the importer since this PR was opened.)

2026-09-15 13:50 UTC, closed without merging