added 3 different formats of email addresses
grokability/snipe-it pull request #8177
Opened 2020-06-25 00:54 UTC by Godmartinz

2020-06-25 18:15 UTC, snipe commented on app/Models/User.php
> +use function GuzzleHttp\Psr7\str;
I don't think we need this use statement - I believe that str helper is available automagically

2020-06-30 06:06 UTC, snipe requested changes
Nice work! 

It looks like maybe your changes from another PR have been lumped into this one? Also I don't think you'd have changed any of the CSS or JS files, so I'm not sure why we're seeing new JS/CSS assets - maybe that's an artifact from the previous PR too? If you can clean this up so that only the current changes for this appear (and add a few tests), I can accept it.

2020-07-07 13:34 UTC, snipe commented
I know this is still a WIP, but just a reminder that I don't see any tests in this PR.

2020-07-10 20:03 UTC, snipe commented on resources/lang/en/general.php
> +    'firstnamelastname'    => 'First Name Last Name (janesmith_@example.com)',
Should there be a trailing underscore here? `janesmith_@example.com`

2020-07-10 20:03 UTC, snipe commented on resources/lang/en/general.php
> +    'firstinitial.lastname' => 'First Initial Last Name (jane.smith@example.com)',
This says "firstinitial.lastname" but the example email address is firstname.lastname

2020-07-10 20:08 UTC, snipe requested changes
Just a few comments to address - thanks!

2020-07-21 17:00 UTC, Godmartinz commented
Translations have been corrected. should be good to go now

2020-07-22 17:51 UTC, snipe commented
Why was AdminLTE.css deleted? I don't think we actually use it (everything should be compiled in), but that change should probably not be in this PR.

2020-07-22 18:22 UTC, snipe commented
Looks like this is addressed in a different PR now

2020-07-22 18:22 UTC, closed without merging