[REVIEW] Feature/docker compose
grokability/snipe-it pull request #9105
Opened 2021-02-05 15:49 UTC by rosscdh

# Description

Added a docker-compose with helper services; as it makes a decent runbook and getting started for developers allot easier

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

docker-compose up
does it work, yes

# Checklist:

- [x ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview

2021-02-09 00:41 UTC, uberbrady requested changes
This looks excellent and I'd love to take it - it seems like a great way to get people up and running with Snipe-IT without making them have to become Docker experts - I'm still not even sure the original way I set up our Docker integration was the right one, tbh.

The only thing that gives me pause with this PR is that there are hardcoded passwords in it, and that can be enormously dangerous. We have users who will gladly peruse the documentation and skip past any advice we were to give, so they can get something up and running - and my concern here is they might get themselves up-and-running with a "well-known" `APP_KEY` (which _may_ be exploitable with remote access) and a "well-known" MySQL password (which probably is only exploitable with local access). I don't think we can put our users in that kind of pisition, even if we plaster warnings all over the place.

Is there any way you can think of to somehow read those values from secrets-store? Or some way we can walk people through easily/quickly setting those values? I'm definitely open to any good ideas here.

2021-02-09 08:15 UTC, rosscdh commented
```
The only thing that gives me pause with this PR is that there are hardcoded passwords in it, and that can be enormously dangerous. We have users who will gladly peruse the documentation and skip past any advice we were to give, so they can get something up and running - and my concern here is they might get themselves up-and-running with a "well-known" APP_KEY (which may be exploitable with remote access) and a "well-known" MySQL password (which probably is only exploitable with local access). I don't think we can put our users in that kind of pisition, even if we plaster warnings all over the place.
```

Yes I completely agree; the problem is that in order to get the artisan command to generate a key you need to have the container running.. in order to get the container running you need to have a key ;) nice catch 22

aside from clearly documenting and or providing a "production" docker-compose which is what the current standard is there is not allot to do about it.

2021-02-09 08:18 UTC, rosscdh commented
another thing i really must recommend is that in docker you 100% only output logs to stdout.. and not to files...  writing logs to files can cause issues in production as your contrainer swells in size..

2021-02-09 08:22 UTC, rosscdh commented
I added a comment near the APP_KEY value that describes how to generate the key

2021-02-09 14:28 UTC, rosscdh commented
```
 I'm still not even sure the original way I set up our Docker integration was the right one, tbh.
```
what were your concerns? happy to chat on topic

2021-02-09 19:29 UTC, uberbrady commented
> another thing i really must recommend is that in docker you 100% only output logs to stdout.. and not to files... writing logs to files can cause issues in production as your contrainer swells in size..

I would be very happy to take a PR that addressed this - from a support perspective it's much easier to get people to look at docker's log output than it is to get them to connect to the container and get the logs out of it. But another wrinkle here is that we also have Apache and/or Nginx output to deal with too (which will *also* bloat the container) - it'd be awesome to get that out of there too. The log output would be pretty...verbose, but hopefully Docker can handle that.

I bet there's something you can do with some of the Laravel env options that might somehow "convince" a logfile to get dumped to stdout.

2021-02-09 19:31 UTC, uberbrady commented
> I added a comment near the APP_KEY value that describes how to generate the key

I think you can generate it even easier than that - using this:

```
docker run --rm snipe/snipe-it
Please re-run this container with an environment variable $APP_KEY
An example APP_KEY you could use is: 
base64:H0h7xYiwLnCQ7vAXW0u0vydukLo1ZLvWHWijGQGV4iw=
```

2021-02-09 19:32 UTC, uberbrady commented
> ```
>  I'm still not even sure the original way I set up our Docker integration was the right one, tbh.
> ```
> 
> 
> what were your concerns? happy to chat on topic

Let's try and chat about this on the Discussions thing (new GitHub feature) - I'll get it started.

2021-03-18 03:37 UTC, snipe commented
Where did we net out on this?

2021-03-18 07:56 UTC, rosscdh commented
I think we were meant to have a discussion.. but didnt setttle on when...

On Thu, Mar 18, 2021 at 4:38 AM snipe ***@***.***> wrote:

> Where did we net out on this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snipe/snipe-it/pull/9105#issuecomment-801595282>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADA6MRG2HICJKO3JPHYEE3TEFYR3ANCNFSM4XE7PLGA>
> .
>

2021-03-18 22:11 UTC, Mateus-Romera commented
Hi everyone, I added support for docker secrets for my use case. I just copied a wordpress function (official dockerhub image) to search and convert variables with the suffix "_FILE" in their corresponding env var. Perhaps this can be a great help for this problem. I wrote more in this issue if you could take a look: https://github.com/snipe/snipe-it/issues/9313

2021-04-06 05:20 UTC, snipe commented
@uberbrady @jerm can we regroup on this so we can either get this merged or not, please? Thanks!!

2021-04-21 04:17 UTC, merged

2021-04-21 05:53 UTC, rosscdh commented
Please note for saltstack users https://github.com/rosscdh/snipeit-formula

2021-04-21 05:57 UTC, rosscdh commented
> #9313

Good work re secrets, usually i use aws secrets manager or vault or similar (git-crypt, if you really must) but that implementation with docker is also good; usually the file is just decrypted/generated and mounted as an env_file in my case.